export { default as Header } from './Header'
export { default as Modal } from './Modal'
export { default as Auth } from './Auth'
export { default as Hero } from './Hero'
export { default as Gallery } from './Gallery'
